-- Seed monologue questions from frontend
INSERT INTO "monologue_questions" ("id", "text", "category", "created_at") VALUES
(7, 'What time do you typically wake up on weekdays?', 'Daily Life', CURRENT_TIMESTAMP),
(8, 'How much time do you spend commuting each day?', 'Daily Life', CURRENT_TIMESTAMP),
(9, 'Do you make a daily to-do list?', 'Daily Life', CURRENT_TIMESTAMP),
(10, 'How many hours of screen time do you have on average per day?', 'Daily Life', CURRENT_TIMESTAMP),
(11, 'How often do you eat out versus cooking at home?', 'Daily Life', CURRENT_TIMESTAMP),
(12, 'Do you exercise regularly (at least three times a week)?', 'Daily Life', CURRENT_TIMESTAMP),
(13, 'How many hours of sleep do you typically get per night?', 'Daily Life', CURRENT_TIMESTAMP),
(14, 'Do you have a set bedtime routine?', 'Daily Life', CURRENT_TIMESTAMP),
(15, 'How often do you feel rushed or short on time?', 'Daily Life', CURRENT_TIMESTAMP),
(16, 'Do you take time for leisure activities each day?', 'Daily Life', CURRENT_TIMESTAMP),
(17, 'Do you rent or own your home?', 'Daily Life', CURRENT_TIMESTAMP),
(18, 'How satisfied are you with your living situation?', 'Daily Life', CURRENT_TIMESTAMP),
(19, 'How often do you do household chores?', 'Daily Life', CURRENT_TIMESTAMP),
(20, 'Do you recycle regularly?', 'Daily Life', CURRENT_TIMESTAMP),
(21, 'How much do you spend on groceries per week?', 'Daily Life', CURRENT_TIMESTAMP),
(22, 'Do you have any pets?', 'Daily Life', CURRENT_TIMESTAMP),
(23, 'Do you have a garden or plants at home?', 'Daily Life', CURRENT_TIMESTAMP),
(24, 'How do you typically manage household repairs?', 'Daily Life', CURRENT_TIMESTAMP),
(25, 'Do you feel safe in your neighborhood?', 'Daily Life', CURRENT_TIMESTAMP),
(26, 'How often do you declutter your living space?', 'Daily Life', CURRENT_TIMESTAMP),
(27, 'What is your current employment status?', 'Daily Life', CURRENT_TIMESTAMP),
(28, 'How satisfied are you with your current job?', 'Daily Life', CURRENT_TIMESTAMP),
(29, 'How do you manage your monthly budget?', 'Daily Life', CURRENT_TIMESTAMP),
(30, 'Do you save money regularly?', 'Daily Life', CURRENT_TIMESTAMP),
(31, 'Do you have any debt?', 'Daily Life', CURRENT_TIMESTAMP),
(32, 'How do you pay your bills?', 'Daily Life', CURRENT_TIMESTAMP),
(33, 'How often do you check your bank account?', 'Daily Life', CURRENT_TIMESTAMP),
(34, 'Do you invest money?', 'Daily Life', CURRENT_TIMESTAMP),
(35, 'How do you plan for retirement?', 'Daily Life', CURRENT_TIMESTAMP),
(36, 'Do you feel financially secure?', 'Daily Life', CURRENT_TIMESTAMP),
(37, 'How often do you socialize with friends and family?', 'Daily Life', CURRENT_TIMESTAMP),
(38, 'Do you participate in any community activities?', 'Daily Life', CURRENT_TIMESTAMP),
(39, 'How often do you use social media?', 'Daily Life', CURRENT_TIMESTAMP),
(40, 'Do you feel connected to your community?', 'Daily Life', CURRENT_TIMESTAMP),
(41, 'Do you volunteer your time?', 'Daily Life', CURRENT_TIMESTAMP),
(42, 'Do you know your neighbors?', 'Daily Life', CURRENT_TIMESTAMP),
(43, 'How often do you have meaningful conversations?', 'Daily Life', CURRENT_TIMESTAMP),
(44, 'Do you feel supported by your social network?', 'Daily Life', CURRENT_TIMESTAMP),
(45, 'Do you prefer online or in-person social interactions?', 'Daily Life', CURRENT_TIMESTAMP),
(46, 'How often do you meet new people?', 'Daily Life', CURRENT_TIMESTAMP),
(47, 'How would you rate your overall health?', 'Daily Life', CURRENT_TIMESTAMP),
(48, 'Do you have any chronic health conditions?', 'Daily Life', CURRENT_TIMESTAMP),
(49, 'How often do you visit a doctor?', 'Daily Life', CURRENT_TIMESTAMP),
(50, 'Do you take any medications regularly?', 'Daily Life', CURRENT_TIMESTAMP),
(51, 'How do you manage stress?', 'Daily Life', CURRENT_TIMESTAMP),
(52, 'Do you practice any mindfulness or relaxation techniques?', 'Daily Life', CURRENT_TIMESTAMP),
(53, 'How often do you drink alcohol?', 'Daily Life', CURRENT_TIMESTAMP),
(54, 'Do you smoke or use tobacco products?', 'Daily Life', CURRENT_TIMESTAMP),
(55, 'How do you maintain a healthy diet?', 'Daily Life', CURRENT_TIMESTAMP),
(56, 'Do you feel mentally and emotionally well?', 'Daily Life', CURRENT_TIMESTAMP),
(57, 'How often do you use the internet?', 'Daily Life', CURRENT_TIMESTAMP),
(58, 'What devices do you use most frequently (smartphone, computer, etc.)?', 'Daily Life', CURRENT_TIMESTAMP),
(59, 'How do you stay informed about current events?', 'Daily Life', CURRENT_TIMESTAMP),
(60, 'Do you trust the information you find online?', 'Daily Life', CURRENT_TIMESTAMP),
(61, 'How often do you experience technical problems with devices?', 'Daily Life', CURRENT_TIMESTAMP),
(62, 'Do you use online banking or shopping?', 'Daily Life', CURRENT_TIMESTAMP),
(63, 'How comfortable are you with new technology?', 'Daily Life', CURRENT_TIMESTAMP),
(64, 'Do you worry about online privacy and security?', 'Daily Life', CURRENT_TIMESTAMP),
(65, 'How do you learn new tech skills?', 'Daily Life', CURRENT_TIMESTAMP),
(66, 'Do you rely heavily on technology for daily tasks?', 'Daily Life', CURRENT_TIMESTAMP),
(67, 'Which artists have fascinated you, and why?', 'Art', CURRENT_TIMESTAMP),
(68, 'What art do you find absolutely terrible, and why?', 'Art', CURRENT_TIMESTAMP),
(69, 'How would you experimentally determine the size of Europe?', 'Art', CURRENT_TIMESTAMP),
(70, 'What are your favorite ice cream flavors?', 'Art', CURRENT_TIMESTAMP),
(71, 'What would you advise Putin right now? What should his strategy be?', 'Art', CURRENT_TIMESTAMP),
(72, 'What are you most afraid of?', 'Art', CURRENT_TIMESTAMP),
(73, 'What was your first artwork?', 'Art', CURRENT_TIMESTAMP),
(74, 'What color is the sky?', 'Art', CURRENT_TIMESTAMP),
(75, 'How high is the sky?', 'Art', CURRENT_TIMESTAMP),
(76, 'What do you daydream about?', 'Art', CURRENT_TIMESTAMP),
(77, 'What is your favorite animal?', 'Art', CURRENT_TIMESTAMP),
(78, 'Which color is important in your life?', 'Art', CURRENT_TIMESTAMP),
(79, 'What distinguishes your art from that of the artist you feel closest to?', 'Art', CURRENT_TIMESTAMP),
(80, 'What materials do you work with?', 'Art', CURRENT_TIMESTAMP),
(81, 'How much money does it take to be happy?', 'Art', CURRENT_TIMESTAMP),
(82, 'Who is the most important person in the world to you?', 'Art', CURRENT_TIMESTAMP),
(83, 'What do you enjoy arguing about?', 'Art', CURRENT_TIMESTAMP),
(84, 'Which of your artworks would you never sell?', 'Art', CURRENT_TIMESTAMP),
(85, 'What is your daily routine?', 'Art', CURRENT_TIMESTAMP),
(86, 'How do you know that you''ve worked too much?', 'Art', CURRENT_TIMESTAMP),
(87, 'How do you know when an artwork is finished?', 'Art', CURRENT_TIMESTAMP),
(88, 'How do you recognize if an artwork (by you or others) is good?', 'Art', CURRENT_TIMESTAMP),
(89, 'How do you express love to another person?', 'Art', CURRENT_TIMESTAMP),
(90, 'Can children create art?', 'Art', CURRENT_TIMESTAMP),
(91, 'How can one recognize the artist''s age from an artwork?', 'Art', CURRENT_TIMESTAMP),
(92, 'What is your understanding of power?', 'Art', CURRENT_TIMESTAMP),
(93, 'What does being rich mean to you?', 'Art', CURRENT_TIMESTAMP),
(94, 'What does being poor mean to you?', 'Art', CURRENT_TIMESTAMP),
(95, 'What is your goal in life?', 'Art', CURRENT_TIMESTAMP),
(96, 'To whom would you sell your soul, and if so, for how much?', 'Art', CURRENT_TIMESTAMP),
(97, 'How would you define "soul"?', 'Art', CURRENT_TIMESTAMP),
(98, 'How many identities do you have, and how would you describe them?', 'Art', CURRENT_TIMESTAMP),
(99, 'How long does it take for you to finish an artwork?', 'Art', CURRENT_TIMESTAMP),
(100, 'How many books have you read?', 'Art', CURRENT_TIMESTAMP),
(101, 'What is in your will (or if you don''t have one, what should be in it)?', 'Art', CURRENT_TIMESTAMP),
(102, 'What is art for you?', 'Art', CURRENT_TIMESTAMP),
(103, 'What would you like to receive as a gift?', 'Art', CURRENT_TIMESTAMP),
(104, 'What do you think about when you brush your teeth?', 'Art', CURRENT_TIMESTAMP),
(105, 'What plants do you have or would you plant in your garden?', 'Art', CURRENT_TIMESTAMP),
(106, 'Is there a legitimate reason for you to kill another person?', 'Art', CURRENT_TIMESTAMP),
(107, 'What would be the harshest punishment that could be imposed on you?', 'Art', CURRENT_TIMESTAMP),
(108, 'What are you afraid of?', 'Art', CURRENT_TIMESTAMP),
(109, 'Which law should be abolished immediately?', 'Art', CURRENT_TIMESTAMP),
(110, 'Which law should definitely be introduced?', 'Art', CURRENT_TIMESTAMP),
(111, 'What superpower do you wish you had?', 'Art', CURRENT_TIMESTAMP),
(112, 'Would you like to live forever, and what would that mean to you?', 'Art', CURRENT_TIMESTAMP),
(113, 'What is something a person you are just getting to know should not find out about you?', 'Art', CURRENT_TIMESTAMP),
(114, 'What is your favorite joke?', 'Art', CURRENT_TIMESTAMP),
(115, 'What do you take responsibility for?', 'Art', CURRENT_TIMESTAMP),
(116, 'What five things would you take with you to a deserted island?', 'Art', CURRENT_TIMESTAMP);

-- Update the sequence to start from the next available ID
SELECT setval('monologue_questions_id_seq', (SELECT MAX(id) FROM monologue_questions)); 